version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: sailetPrisma0327
        databases:
          default:
            connector: postgres
            host: sailet-postgresql.c3nsmeobxucm.ap-northeast-2.rds.amazonaws.com
            port: 5432
            user: sailet
            password: Leebun122!
